// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCavVWqWWdZfz9PXUY04-C3MhzFdgbp1LI',
    appId: '1:1068208810980:web:a2cac0c858e7567809f5f1',
    messagingSenderId: '1068208810980',
    projectId: 'todo-77443',
    authDomain: 'todo-77443.firebaseapp.com',
    storageBucket: 'todo-77443.appspot.com',
    measurementId: 'G-P75TLQL6PC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlGF07iQNQgu7pKtbjMKRnQzzqEoC3EDc',
    appId: '1:1068208810980:android:2607f2e0b680158c09f5f1',
    messagingSenderId: '1068208810980',
    projectId: 'todo-77443',
    storageBucket: 'todo-77443.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAMwzlGeyz00t-UjvwuDdUd62DmZVq0tk',
    appId: '1:1068208810980:ios:3939750e0fbd0fcf09f5f1',
    messagingSenderId: '1068208810980',
    projectId: 'todo-77443',
    storageBucket: 'todo-77443.appspot.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAMwzlGeyz00t-UjvwuDdUd62DmZVq0tk',
    appId: '1:1068208810980:ios:25eceaf4678ea11509f5f1',
    messagingSenderId: '1068208810980',
    projectId: 'todo-77443',
    storageBucket: 'todo-77443.appspot.com',
    iosBundleId: 'com.example.todo.RunnerTests',
  );
}
